package main

import (
	"fmt"
	"sort"
	"strings"
)

//binary shearching ...

func randomNamesGenerator() []string {
	names := "Liam Johnson,Emma Smith,Noah Williams,Olivia Brown,Elijah Jones,Ava Miller,James Davis,Sophia Wilson,Benjamin Moore,Isabella Taylor,Lucas Anderson,Mia Thomas,Henry Jackson,Charlotte White,Alexander Harris,Amelia Martin,William Thompson,Harper Garcia,Michael Martinez,Evelyn Clark,Daniel Lewis,Abigail Lee,Matthew Walker,Emily Hall,Sebastian Allen,Elizabeth Young,Jack King,Sofia Wright,Owen Scott,Avery Green,Jacob Adams,Ella Baker,Levi Nelson,Scarlett Hill,Samuel Rivera,Grace Campbell,David Mitchell,Chloe Roberts,Joseph Carter,Lily Phillips,John Evans,Hannah Turner,Wyatt Torres,Zoey Parker,Carter Collins,Penelope Edwards,Julian Stewart,Riley Flores,Luke Morris,Layla Rogers,Grayson Reed,Nora Cook,Isaac Morgan,Ellie Bailey,Jayden Cooper,Lillian Richardson,Theodore Cox,Addison Howard,Gabriel Ward,Aubrey Brooks,Anthony Bell,Zoey Sanders,Lincoln Price,Stella Bennett,Hudson Wood,Paisley Barnes,Ezra Ross,Natalie Henderson,Leo Coleman,Savannah Coleman,Jaxon Jenkins,Brooklyn Perry,Maverick Powell,Lucy Long,Joshua Patterson,Aaliyah Hughes,Elias Flores,Leah Bryant,Christopher Russell,Audrey Griffin,Andrew Diaz,Anna Hayes,Caleb Myers,Claire Ford,Nathan Hamilton,Skylar Graham,Thomas Sullivan,Violet Wallace,Aaron West,Aria Cole,Isaiah Jordan,Genesis Stone,Charles Simmons,Bella Warren,Eli Reynolds,Caroline Fisher,Ryan Chavez,Kennedy Hunter,Adrian Dunn,Ariana Knight,Jonathan Stephens,Autumn Elliott,Nolan Freeman,Nevaeh Holt,Christian Daniels,Serenity Palmer,Cameron Johnston,Madelyn Lucas,Hunter Kelley,Ruby Spencer,Connor Stephens,Peyton Wells,Santiago Burns,Naomi Arnold,Jeremiah Arnold,Elena Hopkins,Easton Berry,Gabriella Boyd,Angel Stone,Alice Pierce,Roman Riley,Sadie Holmes,Miles West,Hailey Banks,Robert Bishop,Eva Beck,Jameson Sims,Kinsley Montgomery,Greyson Hopkins,Allison Keller,Jason Reynolds,Hailey Fuller,Declan Harper,Eva Franklin,Xavier Barrett,Kylie Mason,Jose Nichols,Julia Weaver,Dominic Payne,Camila Wheeler,Asher Gardner,Piper Fox,Brayden Black,Arianna Rice,Silas Matthews,Melanie Fleming,Micah Weber,Clara Johnston,Gavin Paul,Willow Barber,Bentley Walters,Morgan Watts,Jace Curtis,Isabelle Olson,Kaiden Gilbert,Brielle Snyder,Maxwell Dean,Jasmine Fuller,Ryker Bowman,Reagan Shaw,Beau Chambers,Valentina Hudson,Gael Peters,Juliana Riley,Carlos Marsh,Rachel Burton,Ivan Drake,Freya Stanley,Diego Steele,Maya Walton,Zion Andrews,Eliza Lambert,Maximiliano Matthews,Cora Christensen,Emiliano Nichols,Ayla Pope,Juan Hanson,Andrea Cross,Kingston Dennis,Rosalie Ferguson,Luis Johnston,Harmony Rose,Camden Harper,Sophie Brady,Brody Wolfe,Daisy Burke,Alex Hayes,Georgia Ortiz,Justin Stanley,Luna Wells,Emmett Berry,Alina Rhodes,Malachi Zimmerman,Margot Boyd,Rhett Cummings,Arya Burns,Kael Norman,Lola Beck,Tucker Bush,Amaya Sharp,Andres Hardy,Nina Lambert,Knox Haynes,Jade Armstrong,Finn Brady,Mckenzie Ray,Beckett Owen,Emery Wolfe,Amari Hayes,Brooklynn Barrett,Kaden Carroll,Tessa Brewer,Nash Boone,Lucia Zimmerman"

	//Random 200 names generated by chatGPT
	splited := strings.Split(names, ",") //akes the giant string of names (separated by commas) and splits it into a slice of individual names.
	allNames := []string{}               //Creates an empty string slice to hold the cleaned names.

	for _, v := range splited { //Iterates through each name (v) in the split list and appends it to allNames after cleaning it.
		allNames = append(allNames, strings.TrimLeft(v, ""))
	}
	sort.Strings(allNames) //Alphabetically sorts the names — this is important for binary search to work.

	return allNames

}

func main() {
	nameList := randomNamesGenerator()
	searchedName := "Ruby Spencer" //nome escolhido aleatoriamente

	beginList := 0
	endList := len(nameList) - 1
	operationNumberTillfind := 0

	for beginList <= endList {
		halfOfList := (endList + beginList) / 2
		atualName := nameList[halfOfList]

		if atualName == searchedName {
			fmt.Println("Found name : ", atualName)
			break
		}

		if atualName > searchedName { //se o nome atual for menor que o nome procurado entao a lista comeca do meio pra right
			endList = halfOfList - 1
		}

		if atualName < searchedName { //se o nome atual for menor que o nome procurado entao a lista comeca do meio pra left
			beginList = halfOfList + 1
		}
		operationNumberTillfind++ //incrementacao para ver a quantitade que o programa usou"rodou o loop" ate achar o nome
	}

	fmt.Println("Quantity of operations until find the searching name : ", operationNumberTillfind)
}
